### ISSUE TITLE
Peerio spams any contact list you import

### ISSUE THREAD

**Issue by huitseeker** [PeerioTechnologies/peerio-client#1]
I imported a contact list into Peerio. The whole list got 'invited', by email, to try Peerio 'on my behalf'.

- I do not endorse Peerio, especially in a beta situation where I'm trying import.
- There is no option to avoid the spamming.
- For that matter, there is no advance information that the spamming will occur.

This combination of features (surprise + no option = involuntary) is clearly spamming and thus illegal in a number of countries: https://en.wikipedia.org/wiki/Email_spam_legislation_by_country

**Comment by kaepora** [comment]
Since you are voluntarily importing your contact list, it is the case that you are uploading it in order for invitations to be sent on your behalf.

The mistake we have made here is that we haven't provided a clear warning asking you to confirm that you'd like invitations to be sent. We will add this in an upcoming update and thank you for your feedback.

**Comment by huitseeker** [comment]
I vehemently disagree with the *voluntary* qualification.

There is no part of the software, no text, no dialog, no small script, that tells me any part of the import is "in order for invitations to be sent on your behalf".

There is no preexisting behaviour in other software (e.g. email clients, social networks) that establishes I could have that expectation of silent e-mailing. At best some of those (social networks in particular) could be expected to *ask* me *if* I want invitations to be sent on my behalf.

This is taking my importing of a contact list and equating it with an endorsement. The practice is detestable, involuntary, and illegal.

**Comment by mrben** [comment]
Not just silent emailing but SMSing too. I've got a lot of explaining to do now.

**Comment by jerdog** [comment]
Standard process would be to not only notify that the imported contact list will be spammed, but give users the ability to say "yes please invite" or "no don't". This is poor form for a project wanting to become a good solution for privacy and security.

**Comment by kaepora** [comment]
Hi everyone,

As specified in #10, we've now pushed Peerio 1.0.1 which fixes the miscommunication regarding how contact importing works.

We thought we had clarified enough that importing contacts could invite contacts that were not already Peerio users. Clearly, we messed up and did not clarify this.

With the new update, Peerio will now ask before inviting contacts, and will never send SMS invites at all.

Sorry, everyone. This is an honest miscommunication; we weren't trying to surreptitiously use your contact information. Please make sure you download the latest update before re-using this feature.
