### ISSUE TITLE
Allow users to filter contacts before importing them

### ISSUE THREAD

**Issue by flohdot** [PeerioTechnologies/peerio-client#10]
Client will import CSV, and:

1. Extract only email addresses (ie. ignore phone numbers)
2. Present the user with a list of checkboxes for each email entry in the CSV. 
3. For email addresses associated with the same name/contact, allow the user to choose one email address from a dropdown.
4. Present a user with a "Send Invites" button which also warns that emails will be sent to all selected contacts.

**Comment by kaepora** [comment]
1. Done.
2. Redundant. Users select which contacts they want to include when they're exporting their Google CSV.
3. I've made Peerio automatically select only one email for every contact.
4. Done.
