### ISSUE TITLE
Change "online" icon to settings gear icon

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#101]
Users not able to intuitively find where to change their settings. Consider replacing the "online" icon with a settings gear icon. 

Like a not ugly version of this. 
![2015-01-26_17-47-25](https://cloud.githubusercontent.com/assets/9948915/5910102/ca4870c6-a584-11e4-873b-f4dd891c6d43.png)

If online status is important, the gear could still be green when online and grey when off.

**Comment by flohdot** [comment]
Related to https://github.com/PeerioTechnologies/peerio-client/issues/6 -- the "connection status" indicator could be moved somewhere else where its purpose is clearer.

**Comment by skylarnagao** [comment]
For #6 add light/online indicator below "Preferences" in dropdown menu with word "Online/Offline"

**Comment by skylarnagao** [comment]
This has effectively been solved with the 1.0.4. UI.
