### ISSUE TITLE
Notification when you are only one left in conversation.

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#103]
Right now, if someone leaves a conversation so that you are the only participant, you can still send messages in the thread. A bit confusing, and leads some users to think their messages are going through.

Proposed fix: Grey out send/ack buttons, and replace text-entry box with notification. e.g.

![notiffornoparticipants](https://cloud.githubusercontent.com/assets/9948915/5911486/164005ca-a594-11e4-9a10-4090b61387b5.png)

**Comment by IpsmLorem** [comment]
When does that heppend ? When other participants all destroyed their thread copy ?

**Comment by kaepora** [comment]
Don't forget to assign tickets.
