### ISSUE TITLE
Feature Suggestion: Password Manager UX

### ISSUE THREAD

**Issue by stefanperson** [PeerioTechnologies/peerio-client#109]
it possible (even a good idea?) to add login functionality for @peerio with a password manager to input the username + password? E.g. a button on the @peerio app homepage like the @1password browser extension. I would login/logout a lot more often.

**Comment by IpsmLorem** [comment]
According to me a password manager must not be closely related to the application. All paswword manager handle their own integration to browser anyway.

**Comment by skylarnagao** [comment]
With a quick review of browser-based tools, it looks like services like 1Password and LastPass _at best_ could only auto-fill for the Chrome app.

It looks like LastPass has a separate app that might work for Windows clients: https://helpdesk.lastpass.com/lastpass-for-applications/

Secure Input on OSX may make this difficult as well.

These features may prove more useful on mobile clients.

Investigate.

**Comment by skylarnagao** [comment]
Closing, as desktop integration doesn't seem possible with current offerings, however a separate ticket will be made for mobile clients which **can** support password manager integrations.
