### ISSUE TITLE
Message A selected in list, but message B is shown

### ISSUE THREAD

**Issue by httng** [PeerioTechnologies/peerio-client#110]
It is possible to have message A selected in the list of messages, while the client shows message B to the right.

Precondition: slow, high latency connection

- Click message A
- Wait until it loads
- Click message B
- Click message A again, before message B loads
- After a while, message B will be loaded and shown in the right panel.

Above steps to reproduce it consequently.

However, a more day to day situation will occur often: you browse through the list of messages and notice that the content pane shows messages that do not match the selected message.

**Comment by skylarnagao** [comment]
Unable to reproduce this. Can you verify that this still occurs in version 1.0.4.2?

**Comment by httng** [comment]
Tested, doesn't happen anymore. This issue is solved.
