### ISSUE TITLE
Improve display when searching for contacts

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#114]
If I have a conversation open with someone in the messages tab and start searching for another user, the selected conversation stays open, but with the messages removed. This is a bit confusing, and does not serve an obvious purpose and seems to just waste screen space. Without text, there's no value in potentially using search to cross reference conversations.

e.g. 
![recentmessagesbug](https://cloud.githubusercontent.com/assets/9948915/5961508/28b7f906-a7ab-11e4-9ab5-498a221a47c4.png)

Two possible alternatives:
(1) Maintain view of the previously selected thread with text and response. Search then serves as a way to reference other threads (albeit, only by subject name and participant).

(2) When starting a search, within the messages tab, include a more detailed list of possible conversations. Include thread list with additional information: short preview of the last sent message (if result is a message by contact name), or of the last relevant message (e.g. if result is found within the text of a message exchanged with any user)

**Comment by kaepora** [comment]
This has been fixed since a while back. Forgot to close the ticket.
