### ISSUE TITLE
Please, support firefox

### ISSUE THREAD

**Issue by almet** [PeerioTechnologies/peerio-client#12]
Hi,

Is there a reason firefox isn't supported ? Is that technical ? Thanks :+1:

**Comment by taoeffect** [comment]
Not speaking on behalf of @kaepora, just guessing, but if you're asking about a Firefox browser extension, I'm guessing he chose not to make it because:

- There are clients for OS X, Windows, and Linux as standalone apps (thanks to node-webkit)
- Firefox extensions are a PITA.

**Comment by kaepora** [comment]
@taoeffect is 100% correct.

**Comment by ametaireau** [comment]
Is there any reason this cannot just be a webapp? I don't get why it should be an extension?

**Comment by ametaireau** [comment]
Also, IMO, that's not because it's a PITA to do it on some platform (which indeed is a subjective view) that you should not do it. I may have misread, but it seems the credo of the project is "bring crypto where users are", and well, I'm a user, and like a lot of people (what, 20% of the web approx), I'm using firefox, so I believe you should support it.

**Comment by skylarnagao** [comment]
@anri-asaturov will investigate this. 

Marking as help-wanted.

**Comment by anri-asaturov** [comment]
@ametaireau regarding webapp - it is possible tech-wise, but it does not agree with our security standards.

**Comment by ametaireau** [comment]
@anri-asaturov can you be a little more specific about these standards and what's missing in a web environment?

**Comment by anri-asaturov** [comment]
@ametaireau let me answer you with @kaepora's article: https://www.veracode.com/blog/2014/10/google-chrome-apps-modern-way-build-more-secure-web

**Comment by ametaireau** [comment]
Okay, then we're not calling "web apps" the same things. It's interely possible to have a webapp running in its own process / thread by using packaged apps: https://developer.mozilla.org/en-US/Marketplace/Options/Packaged_apps

**Comment by anri-asaturov** [comment]
@ametaireau ah, yes, you are right, I was sure we are talking about regular SPA websites. We will look into it and I'll try to update you in a month or two, right now we are focused on mobile. Or, If you feel like helping us implement it - we'll be very happy.

**Comment by faust64** [comment]
We can probably close that one, as browser plugins have been abandoned altogether.
Nw.js is used distributed binaries for Windows/Mac/Linux.
