### ISSUE TITLE
Peerio user identifier

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#133]
For now, a user is identified by:
1. a username
2. a minilockID
3. several email adresses
4. a telephone number

I think the only definitive identifier should be the number 1. Every toher one should be modifiable as wishes by the user.
Furthermore, I think that the 4. must never be mandatory and always be replaced by 3.
An email adresse fits well the need of a digital identity, not a telephone number.

**Comment by flohdot** [comment]
The username is already the only definitive identifier. A user can have several email addresses and several phone numbers; one of either phone or email is required but all can be changed. A user is never tied to one particular phone or email forever. The minilock ID will eventually be something that can be changed, though for now it is not. That said, the application is designed with the option of a changed miniLock ID in mind.
