### ISSUE TITLE
Notifs and/or buggy behaviour with address removal

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#143]
<b>Attempt one</b>
(1) Tried to delete one of my addresses.
(2) Was prompted for 2FA code, entered code (no error message, wasn't cutting it close on that code's lifespan either)
(3) Was prompted again for a 2FA code, nothing happened.
(4) Checked my addresses, phone number I tried to delete was still there.

<b>Attempt two</b>
(1) Restarted the client (Mac, 1.0.3.)
(2) Tried to delete the same address.
(3) Was prompted for 2FA code, entered code.
(4) No message appeared.
(5) Checked my addresses, and the address was successfully removed.

Another user experienced the same thing without having 2FA enabled. The issues:
(1) Address didn't delete until restart.
(2) Was prompted for a 2FA code twice for the same task (@flohdot, this may be for you)
(3) Never received a notification that the address removal was either successful or failed.

**Comment by flohdot** [comment]
Seems like this was just a 2fa problem and is now fixed.
