### ISSUE TITLE
Yosemite claims the Mac app from Peerio.com is "damaged."

### ISSUE THREAD

**Issue by jakub-** [PeerioTechnologies/peerio-client#149]
I tried opening the Peerio app for Mac OS X and Yosemite would resist with:

> "Peerio" is damaged and can’t be opened. You should move it to the Trash.

What did the trick for me is running:

> xattr -rc ./Peerio.app

So presumably it's got something to do with Gatekeeper.

Good luck and thank you for Peerio!

**Comment by kaepora** [comment]
Will look into it!

**Comment by flohdot** [comment]
Hi @jakub-, we suspect it may have been a problems with permissions on the Mac executable. A new version has been uploaded. Can you try downloading the Mac app again from our website and let us know if the problem persists? Thanks a lot!

**Comment by jakub-** [comment]
@flohdot Yes! Thank you. :) Keep up the great work, Peerio's awesome.
