### ISSUE TITLE
Unable to disable 2FA

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#152]
User is experiencing a 2FA issue that I haven't been able to reproduce yet, but has provided details and a screenshot of the error message.

(1) User set up 2FA successfully. 
(2) User changed mind, and tried to disable 2FA in the same session, entered code from app, and received this notif:

![2015-02-11_11-01-54](https://cloud.githubusercontent.com/assets/9948915/6150483/b5a2f0aa-b1dd-11e4-8fbb-35b706b3a216.png)

(3) User closed Peerio, reopened, was prompted for 2FA code, and entered the code from the 2FA app successfully.
(4) User tried to disable 2FA again, and again received the same failure to disable notification.

User's connection seems to be fine. 

A second user has experienced a near identical problem and was using Duo Mobile authenticator.

**Comment by skylarnagao** [comment]
Note: User switched to another computer, updated to 1.0.3.1 Windows client, and still experienced the same issue.

**Comment by follydude** [comment]
With the latest peerio mac client 1.0.3.1. I am now no longer able to login at all with duo authenticator. An incorrect code message is returned every time.

I have painted myself into a corner here, as I am unable to disable 2FA.

I will try to restore the last peerio client and use that for now.

**Comment by follydude** [comment]
Correction to my last post. I tried to login again with the 1.0.3.1 client and I was sucessfull this time. I was also able to disable 2FA, so that bug is fixed.

Thanks.

**Comment by flohdot** [comment]
@follydude Good to hear! Thanks for the update!

**Comment by flohdot** [comment]
A fix to this problem has been pushed to production.
