### ISSUE TITLE
double 2fa prompt on authTokenRequest on login

### ISSUE THREAD

**Issue by flohdot** [PeerioTechnologies/peerio-client#154]
When logging in with 2fa enabled, the prompt for 2fa shows up twice sometimes, although I can verify that the server only sends a `424` error once.

**Comment by kaepora** [comment]
Is this happening in the latest build?

**Comment by skylarnagao** [comment]
Just synced latest build, tested, and still experiencing this issue. Only for login, not for adding/removing address info.
