### ISSUE TITLE
slow login / client is firing too many authTokenRequests 

### ISSUE THREAD

**Issue by flohdot** [PeerioTechnologies/peerio-client#155]
Upon signing in I saw tens and tens of `authTokenRequests` go through on the server until they got throttled. The sign in took over a minute. 

![developer_tools_-_chrome-extension___cenfaoedpkaigjmfcicohoogobkejffg_index_html](https://cloud.githubusercontent.com/assets/918747/6222144/744f4c76-b614-11e4-87c1-b0a35429a7c9.png)

This might be a race condition -- I can only make it happen sometimes. I reverted the client back to 1.0.2 (specifically, 49cc6bb929593676bc24a1e71db449615e6ac7dc) and could not reproduce the problem at all, but I'm not sure that this necessarily isolates the fix.

My guess is that client does not wait for `authTokenRequest` to return before making further requests, so every request that is made on client "log in" fires multiple new `authTokenRequests` and so on. It could be that an already slow connection is what triggers the problem.

**Comment by flohdot** [comment]
Tested this a big more and can send you some server logs, if that would be helpful. The gist of what I'm seeing is: the client goes into a loop of `getContacts`, `getSentContactRequests`,  `getReceivedContactRequests`, each sent up to 20 times, and at some point starts making requests that return an error because no authToken is included in the request, while simultaneously making a large number of `authTokenRequests`.

The key is that the client must wait for `authTokenRequest` to return before attempting new requests.

**Comment by kaepora** [comment]
Wow. Investigating.

**Comment by kaepora** [comment]
It seems to be that the server only sends two `authTokenRequest`s during login.

**Comment by kaepora** [comment]
Could not reproduce. Reopen when you have a trace, please.

**Comment by flohdot** [comment]
May have to do with length of contact list... investigating.
