### ISSUE TITLE
Slow load time for users with many contacts

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#164]
Will need to do more tests to confirm it is the number of contacts affecting this, but between a few accounts, with mixed numbers of messages, files, and contacts, only accounts that have long contact lists seem to be having trouble in loading.

@zarag0ziegor has maybe 40+ contacts and his account took 30 seconds from clicking "login" to opening Peerio, and another 8 seconds to actually list the message thread.

In contrast, my account with a dozen contacts took three (3) seconds to load everything.

**Comment by flohdot** [comment]
Same as #155?

**Comment by skylarnagao** [comment]
Yes, marking as duplicate.
