### ISSUE TITLE
Will the server be available?

### ISSUE THREAD

**Issue by vks** [PeerioTechnologies/peerio-client#176]
Will the server be Open Source? Will there be federation support?

Those are crucial for being able to replace email.

**Comment by skylarnagao** [comment]
We have no plans to release the server code at this time, however, the server code is subject to third-party security audits along with the the client code.

Peerio does not have plans for federation. Peerio's centralized structure and control over the environment is maintained to assure greater security by ensuring that all Peerio users are operating with the same security measures. These security measures along with Peerio's code are arduously reviewed by our own developers, the open-source community, and through biannual security audits from independent third parties.
