### ISSUE TITLE
SMS verification fails with non-US number

### ISSUE THREAD

**Issue by mrbiber** [PeerioTechnologies/peerio-client#178]
I tried to add a Dutch mobile number to my Peerio account.

1. Go to account, enter phone number (with +31...)
2. I correctly receive an SMS with a code
3. I enter the code, get the confirmation that it worked
4. when I re-open account settings, the number has changed into a US-number (1 is prepended) and shows up as unconfirmed (code input field still present)

**Comment by skylarnagao** [comment]
Closing, will be addressed with and referenced in #7
