### ISSUE TITLE
Request: more attractive thread UX

### ISSUE THREAD

**Issue by manishvij** [PeerioTechnologies/peerio-client#18]
Thread UX needs a visual design pass. Suggestions:

- rounded corners = more friendly
- less obtrusive borders: e.g. all inverse like iMessage, optionally slightly different blue for header
- my messages should be most prominent color
- lock suffices, remove 'encrypted'

**Comment by kaepora** [comment]
Feel free to submit pull requests or design mockups with suggestions. But I'm closing this issue because it's a bit too general to be productive.
