### ISSUE TITLE
Contact discovery via email address should be optional

### ISSUE THREAD

**Issue by CR0CKER** [PeerioTechnologies/peerio-client#193]
Why is entering an email address necessary? Contact discovery via email address should be optional.

**Comment by IpsmLorem** [comment]
:+1:

**Comment by skylarnagao** [comment]
We require an email or phone number as an auxilary channel for critical communications such as issues concerning account security or if we receive legal requests for information.

Adding an option to disable contact discovery by email/phone is useful though. Re-naming the ticket to reflect this issue.

Also related, #41, do not expose email address in contact information.

**Comment by nilsws** [comment]
Thanks for clarifying. Isn’t the whole point of Peerio and encrypted content to minimize information that can be handed over to third parties? Why put email addresses on record? I would argue that it should be left up to the user whether he or she wants to include an email address for convenience.

**Comment by skylarnagao** [comment]
While we are looking into developing features that reduce metadata footprints such as support for Tor (#11), Peerio is primarily designed to ensure the confidentiality and integrity of messages and files, while also offering features the average user appreciates in communication apps (e.g. push notifications, contact discovery, and account support). We feel that the convenience and usability offerings this brings to average users, along with the previous issues of delivering critical security notices and informing our users of legal requests, are powerful reasons to require this information. 

It's a question of balancing usability, security, and anonymity, and doing our best to enhance all three. It's pretty rough on the support side if a user forgets their username (it happens more than you think) and we can't help them recover it. If we don't have an email or phone number to identify them, that user just lost their account and their data. In contrast, users looking to minimize identifying information in their account can simply register with a throw-away email (e.g. mailinator.com) and disable notifications to that account. 

It may be interesting to add some instructions to the sign-up process indicating how you would go about signing up with a disposable email and why you might want to do this.

**Comment by nilsws** [comment]
I see your points -- thank you for explaining the rationale. I'd still suggest to make entering an email address optional. But it's true that throw-away email addresses are also possible, even though this again puts the burden of achieving privacy on the user, as so many other apps do.

**Comment by faust64** [comment]
We probably forgot to close this, as entering an email of phone number is no longer required registering.
