### ISSUE TITLE
Documentation is outdated, refers to old user interface

### ISSUE THREAD

**Issue by kaepora** [PeerioTechnologies/peerio-client#199]
Following pages need updating to refer to new UI introduced in 1.0.3.

https://peerio.zendesk.com/hc/en-us/articles/203697865-How-do-I-upload-a-file-

https://peerio.zendesk.com/hc/en-us/articles/203700205-How-can-I-sort-my-files-

https://peerio.zendesk.com/hc/en-us/articles/203699205-How-do-I-delete-a-file-

https://peerio.zendesk.com/hc/en-us/articles/203699905-How-do-I-destroy-a-file-

https://peerio.zendesk.com/hc/en-us/articles/204257705-How-do-I-import-contacts-

https://peerio.zendesk.com/hc/en-us/articles/203024429-How-do-I-find-a-contact-s-info-and-my-recent-interactions-with-them-

https://peerio.zendesk.com/hc/en-us/articles/203727895-How-do-I-approve-or-decline-a-contact-request-

https://peerio.zendesk.com/hc/en-us/articles/204057225-How-do-I-sign-up-for-a-Peerio-account-

https://peerio.zendesk.com/hc/en-us/articles/203555339-How-do-I-turn-on-off-sound-notifications-

https://peerio.zendesk.com/hc/en-us/articles/202933129-How-do-I-turn-on-email-or-mobile-notifications-

https://peerio.zendesk.com/hc/en-us/articles/202929509-How-do-I-set-change-or-remove-my-PIN-

https://peerio.zendesk.com/hc/en-us/articles/202926689-How-do-I-change-the-language-Peerio-uses-

https://peerio.zendesk.com/hc/en-us/articles/202932669-How-do-I-remove-an-email-or-phone-number-from-my-contact-info-

https://peerio.zendesk.com/hc/en-us/articles/202931479-How-do-I-change-my-primary-address-

https://peerio.zendesk.com/hc/en-us/articles/203663855-How-do-I-add-or-remove-an-e-mail-or-phone-number-from-my-account-

https://peerio.zendesk.com/hc/en-us/articles/203661715-How-do-I-change-my-displayed-name-

https://peerio.zendesk.com/hc/en-us/articles/202933829-How-do-I-setup-two-factor-authentication-

**Comment by skylarnagao** [comment]
Updated to reflect new UI and changes to passphrase generation in sign up. Additional small changes and edits made.
