### ISSUE TITLE
Unclear way to close "Attach File to Message Window"

### ISSUE THREAD

**Issue by tante** [PeerioTechnologies/peerio-client#2]
After clicking the "attach file to message" icon in a conversation the popup cannot be closed in a discoverable way without attaching a file.

The window should either have an "X" in its upper right corner or a button saying "Cancel" or "close Window without attaching file".

**Comment by Leodagan** [comment]
yes you can clic on the left button and it should bring you back to the previous window.

**Comment by tante** [comment]
You are right. That button behavior is somewhat unexpected though. But thanks, will edit the bug report.
