### ISSUE TITLE
Review dictionaries used for passphrase generation for offensive words

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#211]
Rolled a couple passphrases with some unfortunate words. Will compile an 'offensive' word list to edit out of dictionary.

**Comment by skylarnagao** [comment]
Refer: https://gist.github.com/micahflee/99809514a6b8556ea4dc

**Comment by waabamaa** [comment]
Thanks, yes, please do. I just 'rolled' something that included the word ̈́'f*gg*ts".

**Comment by skylarnagao** [comment]
You can see our current dictionary support here: https://github.com/PeerioTechnologies/peerio-client/blob/master/src/chrome/js/miniLock/phrase.js

The other dictionary linked above consists of the offensive words removed from SecureDrop. Shame that 'fairy' doesn't make it.

**Comment by waabamaa** [comment]
Here's a bunch you may want to delete from that list:

anus,balls,bitch,bitches,breast,breasts,butt,buttock,buttocks,butts,cervical,cervix,cock,cocks,crotch,dick,dong,dyke,dykes,faecal,faeces,fag,faggot,faggots,fagot,fags,ho,hussies,hussy,hymen,hymens,pussy,rape,raped,raping,rapist,rapists,scrotum,semen,sissies,sissy,slut,sluts,taint,taints,testes,testicle,testis,tit,tits,tranny,vulva,whore,whores

**Comment by waabamaa** [comment]
Here are some more you might consider removing. Note that "Gypsy" is an offensive epithet not preferred by Roma/Romani people. You may just want to remove all ethnonyms. Note that "Buddha", "Christian", "Muhammad" do not occur in the list, but the religious words listed below do occur. 

buddhism,buddhist,chink,chinks,christ,eunuch,eunuchs,glans,gypsies,gypsy,hebrews,hindu,hinduism,jap,moses,nazi,naziism,nazis,nazism,pansies,pansy,retard,retarded,retards,shag,shagged,shags,zionism,zionist,zionists,

**Comment by skylarnagao** [comment]
Whoa, thank you for doing the 'dirty' work @waabamaa!

We should see probably organize our dictionary a bit better as well instead of having one 32000 word line. Follow SecureDrop's approach, we may also want to eliminate country names.

**Comment by skylarnagao** [comment]
http://www.bannedwordlist.com/lists/swearWords.txt

**Comment by skylarnagao** [comment]
Generated a masterlist of offensive words across 20+ languages. Has been used to clean all recent passphrase dictionaries. Available here: https://github.com/PeerioTechnologies/peerio-copy/commit/5fe4f436942eb36c66450a3f1486d5fd1302c6bd
