### ISSUE TITLE
[Question] What is the difference between Peerio and Cryptocat?

### ISSUE THREAD

**Issue by interested-party** [PeerioTechnologies/peerio-client#220]
Peerio and Cryptocat have the same creator(s) and also appears to have a similar mission. I love IM clients, and I'd like to see an open source one with OTR and group chats become easier to use and have more features (send images, easier fingerprint verification, etc.). I'm interested in contributing, but it's not clear to me whether I should look at Peerio or Cryptocat.

Is Cryptocat deprecated? Are there some key differences between the two such that both will be valuable going forward? Where should I be contributing?

**Comment by skylarnagao** [comment]
Cryptocat is an independent project from @kaepora, who I believe is still maintaining, but not furthering development on Cryptocat at this point.

Peerio largely offers the functionality of Cryptocat, and extends it with file sharing, file storage, avatar based identity authentication, and persisting user accounts to maintain contact networks, message and file histories, and allow remote data access.

Moving forward, you can expect Peerio to be the primary focus.
