### ISSUE TITLE
Explain what happens when contacts are imported

### ISSUE THREAD

**Issue by CR0CKER** [PeerioTechnologies/peerio-client#225]
Will email addresses be hashed or uploaded in full? What else is being uploaded? Will it be stored? For how long? I have not been able to find answers to these questions.

**Comment by faust64** [comment]
Some of your answers are here: https://github.com/PeerioTechnologies/peerio-client/blob/master/SPECIFICATION.md
Around the `addContact`, you'll see the object describing your contact is not encrypted using miniLock, we're sending a JSON object. HTTPS is (still) the only encryption layer there.

The Contact Import is done around here: https://github.com/PeerioTechnologies/peerio-client/blob/master/application/js/peerio/ui/UI.importContacts.js#L33
It's basically just a loop adding contacts. It only takes selected addesses (`checkedAddresses`). Nothing else is uploaded, than the address we should send an invite to.

These addresses are stored on our side, as we'll eventually need to establish a contact relationship between a newly created account and the inviting part. It is cleared upon confirmation, or should the inviting part drop his request.
As for how long, I could use some confirmation from @flohdot or @anri-asaturov , I think it is kept as long as the invite wasn't confirmed, rejected (by the receiving part) or dropped (by the sending part).

Does this answer your question? Is there anything else I can clarify?

Thanks.
