### ISSUE TITLE
ipcrypt — IP preserving IP encryption

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#226]
Look into ipcrypt for anonymizing IP addresses. https://github.com/veorq/ipcrypt/blob/master/ipcrypt.py

**Comment by faust64** [comment]
Is the client actually needing this? Does it sends IPs?
Rewriting IPs is something we're more likely to do on server logs, or anywhere we would actually see IPs.
AFAIU, the client connects to our server, our ability to see its IP comes from how network works. Not being able to see that IP would prevent us from establishing a TCP handshake.
