### ISSUE TITLE
First conversation received in empty inbox does not show in conversation listing

### ISSUE THREAD

**Issue by flohdot** [PeerioTechnologies/peerio-client#239]
Steps to reproduce:

1. Create a new account
2. Add an existing account as a contact
3. Send a message to the new account (from the existing one -- the new account must be on the receiving end)

The "new message" counter on the message tab is updated, but the conversation does not show up -- restarting the application makes it appear. This only happens when the inbox is empty.

**Comment by anri-asaturov** [comment]
If the existing user accepts contact and immediately sends message to the new user - server fails to notify new user about his accepted contact request, but notifies about message, so new user is not able to decrypt message without miniLockID of his new contact.

**Comment by skylarnagao** [comment]
Seems to be fixed.
