### ISSUE TITLE
returned to computer this morning to see incorrect error

### ISSUE THREAD

**Issue by malgorithms** [PeerioTechnologies/peerio-client#25]
My peerio window was open, and this is what it said:

![image](https://cloud.githubusercontent.com/assets/614943/5758408/6e2e58cc-9c93-11e4-9041-e77c0e81567b.png)

I killed peerio, reopened it, and logged back in fine.

account is `chriscoyne` in case that's helpful.

**Comment by cfinucane** [comment]
I was getting this too, yesterday, in addition to a "too many requests" error.

**Comment by flohdot** [comment]
Yes, this was a bug on our side regarding overly defensive rate limiting. The problem has been fixed.
