### ISSUE TITLE
Request: Ability to make files public

### ISSUE THREAD

**Issue by httng** [PeerioTechnologies/peerio-client#26]
Request: Add functionality to make files publicly available (share by link).

Reasoning:
Sharing files is now possible with selected contacts. For the Peerio encryption to work this is necessary.
However, for this tool to replace Dropbox and/or Gmail, certain features will proof essential, among them the ability to share files with people that you did not beforehand identify as a contact.

**Comment by hdf** [comment]
You did not think this trough. Stuff is encrypted with the public key (miniLockID) of the recipient, so "everyone" would have to have the same private key, to read the file. :)

**Comment by httng** [comment]
Disabling encryption for those files would work as well.

The product is being marketed as a replacement for GMail and Dropbox. If so, this will be essential. However, it introduces all kinds of legal trouble, like notice-takedown procedures etc. which I can imagine Peerio wants to avoid. A creative solution is required, which is why I opened the issue.

For example, include the means to decrypt in the link.

**Comment by hdf** [comment]
In this case the wording of the marketing is probably a bit misleading. Peerio is trying to be an encryption based alternative of said products/services, not actually replace them. Like how torrent does not replace ftp, it's just an alternative for a different niche. (That's what I think at least.)

**Comment by skylarnagao** [comment]
This is a complicated issue for us that has come up in our planning. A big part of Peerio is that everything inside it is encrypted, it is impossible to send unencrypted messages or files. For some less technical users, this is a preventative design feature so a user will never accidentally make their data public.

What might be more in line with this design is sharing via password protected links that a non-Peerio user could open with a password provided by the Peerio user.

**Comment by kaepora** [comment]
As the project's security lead, I am simply opposed to this. With Peerio, we want to create a secure ecosystem where all exchanged content is guaranteed to have high security. We're not going to build explicit channels to allow for selective plaintext publishing.

I'm closing this for now, but I appreciate your suggestions and discussion.
