### ISSUE TITLE
Can you write a BUILD.md?

### ISSUE THREAD

**Issue by micahflee** [PeerioTechnologies/peerio-client#28]
It would be helpful if there were documentation for how to get a development environment up and running, how to build binaries or a chrome extension, and that explains the directory structure of the repo, etc.

Just by looking at the files my guess is that the actual source code is all in src/chrome, while platform-specific files are in src/mac and src/windows. But there doesn't seem to be build scripts to re-build a new Windows binary, for example, and peerio.exe is committed into the repo itself, which is a bit confusing for a source code repository.

**Comment by hdf** [comment]
That exe file is actually node-webkit ( http://nwjs.io/ ) just renamed, icon changed, and compressed with UPX. Zip up the contents of the chrome folder, and name it "package.nw", put it in the same folder as the exe, and it will run.

**Comment by kaepora** [comment]
@hdf Right on the money. Good analysis.

@micahflee is right. I was planning to have a Makefile ready soon, actually, and I'll couple it with a BUILD.md. The build steps are very easy. Expect this to be done soon.

**Comment by hdf** [comment]
I think maybe you could expand this, and write a little tutorial on the workflow and used tools, so that people could more easily get into helping you improve this app. Also for educational porpoises. :P

**Comment by skylarnagao** [comment]
https://github.com/PeerioTechnologies/peerio-client/blob/master/BUILD.md

Closing, but additional input is welcome!
