### ISSUE TITLE
2FA process is unclear to end users

### ISSUE THREAD

**Issue by flohdot** [PeerioTechnologies/peerio-client#29]
The current 2FA process is:

1. 2FA is required to perform changes to user settings. 
2. Users will have to authenticate once per week per server when making requests for authentication tokens. 

(For anyone interested, there is more information in the spec)

The second part of the process is not transparent to the end user and 2fa appears to not work as intended. 

Proposed _provisional_ fix: copy in the client that explains to the user when they will have to use 2fa before a request.

**Comment by skylarnagao** [comment]
Target: 2FA will require an auth-code every-time a user sign in, unless the user specifies otherwise for that particular device.

**Comment by kaepora** [comment]
Please help me out here by formulating a fix so I can implement it quickly instead of deliberating on what exactly it is you want me to do.

**Comment by kyhwana** [comment]
I think it should work the same way google's does for gmail.
Require 2FA for every "login" (or at least program startup) unless the user chooses to save the 2FA auth token. (Perhaps require a PIN/full passphrase each time), which will be saved per device?

**Comment by kaepora** [comment]
Fixed in 90b5fed34220e35b96d8791cd3563a4f16a0d99e.
