### ISSUE TITLE
"Tor Button" — preconfigured Tor proxy setting

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#291]
Related to #290 (Proxy Support). With configurable proxy settings, shouldn't be hard to offer a pre-configured proxy setting that directs Peerio traffic over the Tor network. 

Users would still need to download Tor and run it alongside Peerio for the proxy to have effect. Clicking the Tor Button should load an info modal instructing the user on this, and also link to torproject.org for download of Tor.

A Tor connection status indicator would be valuable here. https://check.torproject.org/

**Comment by skylarnagao** [comment]
Related #11

**Comment by faust64** [comment]
A Tor button implies embedding Tor client into ours, AFAIU. Not sure it makes sense.
