### ISSUE TITLE
HTTPS Everywhere Proxy

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#292]
HTTPS Everywhere Proxy for URLs pursued from Peerio: https://github.com/equalitie/HTTPS-Proxy

**Comment by faust64** [comment]
I think I already asked about details about this, ...
AFAIU: all our services are served through https. The few of them we also serve via HTTP without forcing a redirect: we do it for good reasons.
Meanwhile, running a process intercepting HTTP traffic doesn't sound like a safe long-term plan. Closing.
