### ISSUE TITLE
UI updates on settings change even if 2fa fails

### ISSUE THREAD

**Issue by flohdot** [PeerioTechnologies/peerio-client#30]
Steps to reproduce: 

1. Turn on 2FA
2. Enter preferences, uncheck the notifications checkbox
3. Exit out of the 2FA dialog when it comes up

Expected result: Notification checkbox re-checks itself upon 2FA failure
Actual result: Notification checkbox remains unchecked even after exiting preferences and going back in. 

The notifications preference is not actually updated without validating 2fa, but the UI does revert to not reflect that the change in preferences failed.

**Comment by kaepora** [comment]
Yes. This should be fixed as it causes an ambiguous user experience. Will handle it.

**Comment by flohdot** [comment]
The same applies when changing preferences (e.g. firstname) and not submitting the change. Closing the modal should reset the fields to their previous value.

**Comment by kaepora** [comment]
:star:
