### ISSUE TITLE
Peerio closes application when last window is closed on OS X

### ISSUE THREAD

**Issue by Pacoup** [PeerioTechnologies/peerio-client#31]
By default, applications on OS X stay opened even when their last window is closed. This is important because this is essentially how the minimize behaviour on OS X works. The real minimize causes an extra icon to appear in the dock, so no one uses that.

For instance, if I close my iTunes window, it keeps playing in the background, and if I click on the dock icon, it simply re-opens the window exactly where it was (in iTunes's case, the window is kept in memory, but Cocoa (i.e. normal Mac apps) allows developers to choose a different behaviour; e.g. the Finder opens an entirely new instance of the default window).

Peerio should behave the same way as iTunes because it allows making the window hidden while keeping Peerio open and capable of receiving messages without having to cmd+h (hide) the window every time. This is also expected behaviour for most apps on OS X. Very few users know or use cmd+h and most will be confused when they find out the app had actually been closed when they closed the window.

**Comment by kaepora** [comment]
As far as I'm aware, this is a limitation having to do with `node-webkit`.

**Comment by Pacoup** [comment]
Or not. The NW.js devs say it's possible: https://github.com/nwjs/nw.js/issues/1788
