### ISSUE TITLE
2FA and ignored notifications (?)

### ISSUE THREAD

**Issue by faust64** [PeerioTechnologies/peerio-client#312]
It's been twice in a couple days, that someone sends me either an invite or a message while I'm being asked to re-send my 2FA (long inactivity on the client).
Once I enter my code, I can't find the new message or contact request.
Switching tabs back and forth don't refresh the items displayed, I'm left with a 'inconsistent' view of my contacts, messages (and probably files).
I have to log out & log back in, to either read my message or confirm the received contact request.

**Comment by faust64** [comment]
Yesterday, after a long inactivity, I had to re-validate my 2FA code.
Then, trying to send a message, I ended up with some error. I had to close and restart my client to send my message.

**Comment by flohdot** [comment]
Long inactivity probably means your authTokens are expired but the client has no logic in place for dealing with that... Rewrite pending...

**Comment by faust64** [comment]
closing/probably won't be much new devs for that client.
