### ISSUE TITLE
Missing Text

### ISSUE THREAD

**Issue by Oatmas64134** [PeerioTechnologies/peerio-client#328]
While loading Peerio from Chrome, the buttons are missing text. Is this intended?

**Comment by skylarnagao** [comment]
Could you provide a screenshot of what's happening?

**Comment by Oatmas64134** [comment]
How would I do that on chrome?

**Comment by skylarnagao** [comment]
Guide to screenshots:

Windows: http://windows.microsoft.com/en-us/windows/take-screen-capture-print-screen#take-screen-capture-print-screen=windows-8

OSX: https://support.apple.com/en-us/HT201361

Chromebooks: 
![2015-12-22_13-04-33](https://cloud.githubusercontent.com/assets/9948915/11962264/8fbfebec-a8ac-11e5-9180-75b64c881ccc.png)

**Comment by Oatmas64134** [comment]
Thank you

**Comment by Oatmas64134** [comment]
![screenshot 2015-12-22 at 1 05 25 pm](https://cloud.githubusercontent.com/assets/8702646/11962288/b2ddef7a-a8ac-11e5-8abe-6cf83fe6dec0.png)

**Comment by skylarnagao** [comment]
This is definitely not intended! I see you're running 1.2.0, can you tell me which operating system (including version number) you're on?

**Comment by skylarnagao** [comment]
Also, what language is your system set to?

**Comment by Oatmas64134** [comment]
English

**Comment by Oatmas64134** [comment]
My version is 47.0.2526.106 (Official Build) (64-bit)

**Comment by skylarnagao** [comment]
@Oatmas64134 Are you running Peerio for Chrome on OSX, Windows, Linux, or ChromeOS?

Maybe silly question, but did you get the app from https://peerio.com // The Chrome Web App store?

**Comment by flohdot** [comment]
Hi @Oatmas64134, I briefly experienced this problem, and found that restarting Chrome altogether fixed it. Have you given that a shot?

**Comment by Oatmas64134** [comment]
Yes, with no luck

**Comment by Oatmas64134** [comment]
Well, I got it fixed. I got it from peerio.com. Thanks for your help!

**Comment by skylarnagao** [comment]
@Oatmas64134 Glad to hear :smiley:
