### ISSUE TITLE
[Linux Packaging] GnuTLS recv error (-9): A TLS packet with unexpected length was received.

### ISSUE THREAD

**Issue by marianoju** [PeerioTechnologies/peerio-client#329]
Installation [as instructed for Trusty](https://linux.peerio.com/trusty/) fails. 

> user@box2:~$ sudo apt-get install peerio-client
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   peerio-client
> 0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
> Need to get 31,6 MB of archives.
> After this operation, 111 MB of additional disk space will be used.
> Get:1 https://linux.peerio.com/trusty/ trusty/main peerio-client i386 1.2.0-1 [31,6 MB]
> Err https://linux.peerio.com/trusty/ trusty/main peerio-client i386 1.2.0-1    
>   GnuTLS recv error (-9): A TLS packet with unexpected length was received.
> E: Failed to fetch https://linux.peerio.com/trusty/pool/main/p/peerio-client/peerio-client_1.2.0-1_i386.deb  GnuTLS recv error (-9): A TLS packet with unexpected length was received.
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by faust64** [comment]
Weird, I have it working on a couple laptops.
Could you tell me which versions of libgnutls do you have installed on your system (`dpkg -l | grep libgnutls`)?

Short answer: you may modify your `/etc/apt/sources.list.d/peerio.list`, replacing `https` with `http`. `apt-get update` again, then you should be able to `apt-get install peerio-client`.

Thanks for your feedback.

**Comment by faust64** [comment]
According to there: http://arashmilani.com/post?id=21
It could be a certificate validation problem.
Additional question: do you have `ca-certificates` installed (`dpkg -l | grep ca-certificates`)?

**Comment by faust64** [comment]
Closing: missing details on the specifics, still downgrading to http obviously fixes.
I might just remove https from all docs, leave it to user's discretion. Our SSL configuration being what it is, protocol and cipher issues are relatively usual anyway.

**Comment by marianoju** [comment]
I have been gone for the holidays, and I am now catching up. 

As to your questions, I do have installed: 
> ii  libgnutls-dev                                               2.12.23-12ubuntu2.3                                 i386         GNU TLS library - development files
> ii  libgnutls-openssl27:i386                                    2.12.23-12ubuntu2.3                                 i386         GNU TLS library - OpenSSL wrapper
> ii  libgnutls26:i386                                            2.12.23-12ubuntu2.3                                 i386         GNU TLS library - runtime library
> ii  libgnutls28:i386                                            3.2.11-2ubuntu1.1                                   i386         GNU TLS library - main runtime library
> ii  libgnutlsxx27:i386                                          2.12.23-12ubuntu2.3                                 i386         GNU TLS library - C++ runtime library
> ii  ca-certificates                                             20141019ubuntu0.14.04.1                             all          Common CA certificates
> ii  ca-certificates-java                                        20130815ubuntu1                                     all          Common CA certificates (JKS keystore)

After manually editing /etc/apt/sources.list.d/peerio.list I have been able to apt-get install peerio-client. Thank you!

**Comment by faust64** [comment]
Well, it looks very much like my current laptop. Except you're only showing i386 packages, I'd guess you're not on a 64b system. It shouldn't be a problem.

If you followed our instructions, you were able to open some https socket with wget, downloading our GPG public key. Thus, I'm not sure I get why your apt would fail connecting.

That's a sign. I'll update our repository docs, so everyone use http.
Thanks for your follow-up!
