### ISSUE TITLE
"Add Contact" button does nothing when username is too long?

### ISSUE THREAD

**Issue by cfinucane** [PeerioTechnologies/peerio-client#33]
If I put in `aaaaaaaaaaaaaaaa` as the username to add as a contact, and click "Add Contact", nothing happens at all.  I would expect to see either success or an error.  On OS X.

**Comment by kaepora** [comment]
Thanks, will look into this.

**Comment by bnvk** [comment]
I can confirm something similar as well as some extra details!

- Unable to add contact "@zmanian"
- Provides no feedback as to why

![screen shot 2015-01-17 at 8 20 04 pm](https://cloud.githubusercontent.com/assets/48677/5790033/e2d0948e-9e86-11e4-8555-77df7bb7d79a.png)

However, if I entered an email address (that may or may not belong to this user) it told me "An invite has been sent"

Also, If I close the "Add Contact" modal and go to elsewhere in the app, then navigate back to Add Contact the form field is still populated

Not sure if #44 is related or not!

**Comment by kaepora** [comment]
@bnvk Why are you adding an `@` before contacts? This isn't Twitter!

**Comment by bnvk** [comment]
@kaepora oh, um, hehe, I guess I'm doing it because it's kinda standard practice on many of these sites (like Github, Facebook, etc...) when referencing a user in a text field by "username" kinda like how you just referenced me. While this is not an action like adding a contact, I think my natural instinct was just prepend the @ 

I just tested adding the same contact without the @ as well as `aaaaaaaaaaaaaaaa` and both contacts seemed to "send the request" just fine!

**Comment by kaepora** [comment]
@bnvk I think we should make Peerio not freak out when there is a `@`. Will fix this.

**Comment by cfinucane** [comment]
Yeah, `aaaaaaaaaaaaaaaa` works for me right now but adding more A's still results in the Add Contact button doing nothing when I click on it (e.g. I tested by just doubling the number).

**Comment by bnvk** [comment]
@kaepora sounds good :+1: great work so far on Peer.io, excited to see it develop and use it!

**Comment by kaepora** [comment]
@bnvk Very much appreciated. It would be amazing to collaborate with you and the Mailpile team in the future. Much respect! Very appreciate! Wow.

**Comment by skylarnagao** [comment]
Usernames can only be 16 characters long. We should add a notification saying "This does not appear to be a valid username" in these instances.

However, I just tried to add aaaaaaaaaaaaaaaa (16 char) and Peerio gave me a notification saying "contact request sent", except this user does not exist and does not show up in my pending contacts list. We should also add a notification for non-existent users. "This username does not appear to be registered with Peerio"

**Comment by kaepora** [comment]
Namely, the +16 char drama has been fixed, and Peerio won't freak out anymore when there's an `@` prepended to the username we're adding.
