### ISSUE TITLE
Download Peerio over Tor

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#334]
Issue received from member of Freedom of the Press Foundation.

"I'd like to be able to download Peerio packages over Tor, however, your current usage of Cloudflare prohibits me from doing so. (Unfortunately, Debian's apt-get and aptitude cannot solve CAPTCHAs.) There are two ways I can think of that you could solve this with:

(i) whitelist _most_ Tor exit nodes with https://github.com/DonnchaC/cloudflare-tor-whitelister (most because CF currently limits the number of IPs you can whitelist--I also have heard they are working on a built-in setting to allow Tor users, but don't know when this should be expected. See the README for more)

(ii) Host hidden service repos. This option is maybe a bit more work, but would be awesome. If you want to, you can still use HTTPS with an EV cert for the .onion.

Please consider the importance of allowing people to download Peerio anonymously and thank you :-)"

**Comment by faust64** [comment]
(i) addressed by moving our repository somewhere else.
may address (II) later on (https://github.com/PeerioTechnologies/peerio-ansible/issues/34)
