### ISSUE TITLE
Install Failure - Xubuntu 15.10

### ISSUE THREAD

**Issue by nwaringa** [PeerioTechnologies/peerio-client#336]
I walked through your Ubuntu 15.10 package install and have a failure (using the Ubuntu 15.10 directions). The package downloads and installs clean but the Peerio interface throws me a "Critical Update Available" dialog when trying to open.

![peerio_001](https://cloud.githubusercontent.com/assets/16107123/13885997/5ba52400-ed0b-11e5-84cb-caaaef8b6a23.png)

**Comment by faust64** [comment]
Hi,

You should be able to "escape" that screen. Although it is true, Linux packages are out of date.
Main reason being that even if you did build them, there's no guarantee they would work (as per https://github.com/PeerioTechnologies/peerio-client/issues/335).

Considering you are running ubuntu 15.10, and assuming you did upgrade your system in the last couple months, then the libnss version you have installed is 3.21, which we know prevents the socket.io client library to establish its SSL handshake to our service.

As of today, debian jessie is pretty much the last linux package still working. Pending further investigations regarding our failure to establish this handshake.
In the meantime, the chrome extension will work.

Apologies for the inconvenience. Thanks for bringing it up.

Regards.

**Comment by faust64** [comment]
You should be able to fetch 1.4.1 from our repository.

Regards.
