### ISSUE TITLE
Russian wordlist still includes some offensive words

### ISSUE THREAD

**Issue by iamale** [PeerioTechnologies/peerio-client#337]
Here's what I got today:

![screenshot_2016-03-29_07-01-56](https://cloud.githubusercontent.com/assets/1298948/14098890/7200a812-f591-11e5-803e-707db5a53941.png)

Шлюха is basically 'slut, whore' in Russian. After viewing [the word list][wl], I've also discovered 'сука', which is also considered offensive in some contexts (i. e. when referring to a woman).

[wl]: https://github.com/PeerioTechnologies/peerio-client/blob/master/application/js/peerio/phrase/dict/ru.txt

**Comment by flohdot** [comment]
Thanks, @iamale, I added those words to the excluded word list. We'll regenerate the dictionaries without those words for the next release.

**Comment by iamale** [comment]
There are also some word forms of these two words included (`шлюхи`, `шлюшка`, `сучка` etc.). If you want, I can try to enumerate them all, but basically, `(шлю[хш]|суч?к).*` should do its job.

**Comment by anri-asaturov** [comment]
Thanks, @iamale, we'll ask one of our russian speaking developers to review the list finally :-D
