### ISSUE TITLE
True portability on Windows

### ISSUE THREAD

**Issue by sergeevabc** [PeerioTechnologies/peerio-client#344]
Dear team behind Peerio,
I tried following [these instructions](https://peerio.zendesk.com/hc/en-us/articles/204169869-How-do-I-install-Peerio-to-a-USB-thumbdrive-) to make Peerio portable without USB thumbdrive, but simply extracting to some folder. However ```peerio.exe``` creates profile inside ```C:\Users\...AppData\Local\Peerio``` after launch, but not inside its own folder as expected. Could you be so kind to fix it?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by ebilg** [comment]
Hi sergeevabc,

Thanks for getting in touch! Currently this is the level of portability we are supporting on Peerio's standalone version. We are working on extending Peerio Ghosts to add more features for users who don't wish to install software locally and we're also considering the change you suggest for a bigger update coming later.
