### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by ovalseven8** [PeerioTechnologies/peerio-client#36]
Hello,

I have created an almost complete German translation file. 
Only a few senteces haven't been translated yet. But I think, also with the community, the file should be finished soon. 

If you like, @kaepora, you can add the German translation file.
http://pastebin.com/nPmsw1S0

ovalseven8

**Comment by kmindi** [comment]
@ovalseven8 good work. @httng I will integrate @ovalseven8 s translation into mine and update the pull request ;)

**Comment by skylarnagao** [comment]
Closing, thanks all! Translations are now done via Transifex: https://www.transifex.com/otf/peerio/
