### ISSUE TITLE
Add option to disable sounds.

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#40]
Add option to preferences to be able to disable notification sounds.

**Comment by manishvij** [comment]
+1

**Comment by Tiago235** [comment]
+1

**Comment by kaepora** [comment]
@flohdot I've implemented this in the client in 23e68aaf8d4cad5ebbb438f576c6eaf1a16bfdc6, however it seems that the server is not saving the updated `useSounds` value. If I send it a request updating to `useSounds: false`, the server accepts it with a `200` but will still send `useSounds: true`.
