### ISSUE TITLE
Request: Add "Cancel" button when attaching file to message

### ISSUE THREAD

**Issue by christianlundkvist** [PeerioTechnologies/peerio-client#43]
Right now if I click "Attach file" in Messages and then change my mind I have to make sure all files are unchecked and then select "Attach Selected Files". This is of course logically correct but it would be clearer to have a "Cancel" button or the ability to hit Esc to go back to the message screen. I myself hit Esc first and then scanned for a Cancel button before working it out.

**Comment by Leodagan** [comment]
I think this is the same as #2 .

**Comment by christianlundkvist** [comment]
Yes, you're absolutely right. Must have missed that one, sorry! Closing this.
