### ISSUE TITLE
The "To" field only shows 5/6 chars of @username

### ISSUE THREAD

**Issue by bnvk** [PeerioTechnologies/peerio-client#44]
If I try to send a message directly to a user via "Message -> Compose" the username is chopped off in the "To" field

![screen shot 2015-01-17 at 8 20 27 pm](https://cloud.githubusercontent.com/assets/48677/5790035/eaf895d0-9e86-11e4-96c9-888b8c773c83.png)

Upon trying to send a message to this contact, I get the following "Message has no recipients"

![screen shot 2015-01-17 at 8 28 18 pm](https://cloud.githubusercontent.com/assets/48677/5790049/946503a6-9e87-11e4-8ba4-0e75f416380b.png)

**Comment by skylarnagao** [comment]
@bnvk Curious, what scren size and resolution were you using when this happened?

**Comment by bnvk** [comment]
@skylarnagao I'm using a MacBook Air 13" display (1440 x 900)

**Comment by Mercedes-Joy** [comment]
I encountered the same issue. 
When Composing a message I encounter the following. The text input box for Recipient is clipped to six characters long(visually) . However when I send, I am prompted for a recipient and msg will not send.
my settings are:
 WindowsXP-Home-SP3
Google Chrome Version 39.0.2171.99
on a Samsung N120 notebook, screen resolution 1024x600.

I was informed the development team has been notified.

**Comment by kaepora** [comment]
Will look into this.

**Comment by skylarnagao** [comment]
Entry field viewing fixed bb9037d

The "message has no recipients" notice is because the contact entered is not one of your contacts (no valid usernames or emails that start with "@")

Added issue #127 to help identify incorrect/unavailable contact
