### ISSUE TITLE
Peerio notifies of new messages via email even when the client is open

### ISSUE THREAD

**Issue by tante** [PeerioTechnologies/peerio-client#5]
Peerio is somewhat spammy with email notifications.

Emails should only be send when the conversation (better even the peerio app) isn't opened. Getting an email for all those "chat" messages you've already seen is annoying.

**Comment by 0xabad1dea** [comment]
The person I just had my first chat with and I just independently came to this conclusion and they suggested a three-level email setting rather than a two-level, ie, all emails, only emails for messages I missed, no emails

**Comment by manishvij** [comment]
+1. OS X push plus email is too much, should default to not sending email. Also email leaks the fact that you got a message.

There are better ways of getting viral spread: e.g. make first run experience easier, let user send test message to contact before contact signs up.

**Comment by hdf** [comment]
+1
Mail notifications of arrived messages should definitely be optional.

**Comment by flohdot** [comment]
@hdf You can switch off email notifications in the Preferences panel (found by hovering over your name in the top right corner). 

More precise, configurable notifications are definitely something we will work on soon.

**Comment by Tiago235** [comment]
+1

**Comment by kaepora** [comment]
@flohdot Assigning this to you. Here's how I propose you fix this: Just make it so that if a username has submitted a valid `authToken` in the past `n` minutes (10? 15?), don't send notification email.

**Comment by hdf** [comment]
Not sure that's such a good idea. What if someone just signs in, sees that there are no new messages, signs out, and a minute later a message arrives? I think maybe you should implement a heartbeat protocol for this sort of thing. At 30s or 1 minute resolution?
