### ISSUE TITLE
File destroy sometimes will still list destroyed file with loading circle

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#50]
User reported:

> I tried to “destroy” a sent file on a remote machine. Although the file was destroyed and 
> couldn’t be downloaded any more, it was still listed in the Files tab. I first thought it would 
> just take some time to resync but it remained in the list until I restarted my peerio client. 
> The destroyed file had a loading circle but never got removed from the list.

If a user tries to download a file that has been destroyed, an error modal should pop up and the files listing should be updated.

**Comment by kaepora** [comment]
@skylarnagao Did you attempt to reproduce this issue before opening a ticket?

**Comment by kaepora** [comment]
From Vincent:

> Open 2 peerio windows with 2 different users. Send a file from user 1 to user 2 while looking ath user 2's file tab. You will see that unless you restart the client, the file in user #2 is still there and that if you try to click on it it just hangs there. It should disappear instead of still show up there.

**Comment by kaepora** [comment]
Actually, it seems @zarag0ziegor and @skylarnagao are describing two different problems?
