### ISSUE TITLE
If you're italian, it's likely your lastName won't let you sign up.

### ISSUE THREAD

**Issue by giuscri** [PeerioTechnologies/peerio-client#53]
Here [1] `ng-pattern` should be enriched such to match also characters that are very common in european languages. Say, `ò`, `à`, `ì`, ...
In my country lots of last names end with those letters. It would be nice to at least add a tip when user enter a last name that's not *valid*.
Otherwise, curious people in a hurry (me) will think this software simply does not work! :)

**EDIT**: is it even necessary to use a `ng-pattern`? Why matching the fields character by character? XSS?...

--
[1] https://github.com/PeerioTechnologies/peerio-client/blob/master/src/chrome/index.html#L131

**Comment by kaepora** [comment]
@flohdot

**Comment by flohdot** [comment]
This has been modified on the server-side. The client will have to reflect the changes as well.

**Comment by kaepora** [comment]
@flohdot What's the new regular expression you're using on the server? How am I supposed to update the client without it?

**Comment by flohdot** [comment]
@kaepora `^[a-zãâàâåáéèêëîïôûùüÿýçñæœößøòôõóìîíùûúà .\-']{1,20}$`

**Comment by kaepora** [comment]
@flohdot Thanks!

**Comment by skylarnagao** [comment]
Received request to add non-latin and latin-extended characters to extend name support. Maybe all of Latin Extended-A would be a reasonable range: https://en.wikipedia.org/wiki/Latin_Extended-A

**Comment by spitfire** [comment]
Peerio didn't accept my surname too - I'm Polish. The letter causing this to happen was 'Ś', you might also want to check:
ąćęłńóśżź

**Comment by skylarnagao** [comment]
Fixed.
