### ISSUE TITLE
Add "resend confirmation code" button to sign-up.

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#56]
Add button to "Send another confirmation code" to signup. 

A few users reported not receiving confirmation codes on their first attempt, but all received on second attempt. Interestingly, all users reporting this were using custom domain names. 

Button addresses this as well as expired confirmation codes related to #37

**Comment by kaepora** [comment]
Assigning this to @flohdot as I believe it requires some server call.

**Comment by skylarnagao** [comment]
Deprecated
