### ISSUE TITLE
unclear green circular icon in the top right corner

### ISSUE THREAD

**Issue by tante** [PeerioTechnologies/peerio-client#6]
The green icon in the top right corner reminds of the online-status-indicators some instant messengers use. 
But you can only log out, not change your status, so it's unclear what that icon is communicating. Does it mean that peerio servers are working?
It's a little confusing.

**Comment by kaepora** [comment]
It's a connection health indicator. Turns red if your Internet connection is dropping out or if the server is offline.

**Comment by hdf** [comment]
So, needs a mouse over bubble that says: "Connection status: OK", or something?

**Comment by kaepora** [comment]
Yeah sure, that's a good idea.
