### ISSUE TITLE
Do not send email/SMS notifications if user is online/reads

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#60]
If user is using Peerio and reads/acknowledges messages, say within a few minutes of receipt, do not send email/SMS notifications.

**Comment by mrbiber** [comment]
+1 for delaying messages by about a minute and sending them only if there is no client interaction in between.

**Comment by Tiago235** [comment]
+1!

**Comment by IpsmLorem** [comment]
Closely related to #5

**Comment by kaepora** [comment]
Duplicate of #5, actually.
