### ISSUE TITLE
Chinese characters failing to display for some users

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#62]
Group of users communicating in Chinese found that for 7/10 users, Chinese characters displayed as white blocks in Peerio, but could be copy+pasted and read in Word. For the other 3/10 users, Chinese characters seemed to work.

User submitted screenshots:
![chinesechar1](https://cloud.githubusercontent.com/assets/9948915/5840776/fec41d1e-a165-11e4-899d-8b6ee0a0f501.png)
![chinesechar2](https://cloud.githubusercontent.com/assets/9948915/5840778/00f1b97a-a166-11e4-97b2-96d880e6d506.png)

**Comment by skylarnagao** [comment]
Follow up on this, all 10 users were on Win7, Chinese language setting.

From user: "I have a gut feeling of this bug is somehow related to the character colour/background 
setting of Peerio."

**Comment by kaepora** [comment]
Could not reproduce.
