### ISSUE TITLE
Attach document icons are inconsistent.

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#72]
Tiny issue brought up by users.

Attach files button has paperclip.
![peerio](https://cloud.githubusercontent.com/assets/9948915/5863146/5e41d81e-a245-11e4-8536-b8a0c4113315.png)

But attach files button is document.
![peerio](https://cloud.githubusercontent.com/assets/9948915/5863293/81c59a5e-a246-11e4-9c40-390c9d1142de.png)

Paperclip is more commonly understood in use, as well as makes more sense for attaching any file, as opposed to documents only. Usability for e-v-e-r-y-b-o-d-y.

**Comment by kaepora** [comment]
Paperclip icon is made out of thin lines, looks barely visible on light background.
![image](https://cloud.githubusercontent.com/assets/9953/5864101/5c5ae9ac-a27f-11e4-91ed-8c014b3a9b7f.png)

I knew there was a reason I didn't do this.

**Comment by skylarnagao** [comment]
Reopening with late milestone. Another user pointed out the paper with a folded corner is often used for "New document" rather than "attachment".

Should consider new design if the current one doesn't work.

**Comment by skylarnagao** [comment]
solved.
