### ISSUE TITLE
Bad message display

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#77]
Select a message in the "All messages" view.
Click on "New Messages".
The view only display the selected message and not the unread one.

**Comment by kaepora** [comment]
Yes, the selected message will always be displayed.

**Comment by IpsmLorem** [comment]
Then I do not understand the meaning of "New messages" tab view. What is the feature ?

**Comment by skylarnagao** [comment]
Reopening. @IpsmLorem is right. Marking for a later milestone, but when you go to the "new messages" tab you should only see unread messages.

**Comment by skylarnagao** [comment]
Closing. New client uses `inbox` and `All messages`

`inbox` = all unsorted messages with new messages always marked and at the top
`All messages` = all messages in the account, across all folders, unread and read
