### ISSUE TITLE
A default "Archive" folder

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#81]
Maybe a default "Archive" folder for processed messages could be added

Related to #54

**Comment by skylarnagao** [comment]
Can you specify what you mean by "processed"?

Is the idea that this would clean your inbox by pushing old messages to an archive, without deleting them?

**Comment by IpsmLorem** [comment]
Yes that is the idea. Some email must be kept for later reference but be send out of the view to keep focusing in the inbox.
"inbox zero" paradigm

**Comment by skylarnagao** [comment]
Closing. With folders in place, user can create an archive folder to sort old messages and clean inbox
