### ISSUE TITLE
Improve file and message sync across multiple devices

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#88]
If you have multiple instances of Peerio open, say a laptop, desktop, and mobile, when you upload a file or send/receive messages on one of the devices, it does not sync to the other devices until restarting Peerio.

Improve sync so it is files and message threads are updated live in all Peerio windows a user has open across all devices.

**Comment by kaepora** [comment]
Yes, this is important.

**Comment by kaepora** [comment]
I'd like the server to send some kind of push notifications to all logged in users once the file list changes due to a file being uploaded by that user (not needed for receiving files from others). Similar to when you receive a new contact, etc.

**Comment by flohdot** [comment]
The server is now providing a `uploadedFilesAvailable` event (in pre-prod). This event fires when the number of uploaded files changes (increases _or_ decreases). This event applies only to a user's own files, not files they have received from other users. 

Regarding message sync, the `modifiedMessagesAvailable` event fires when the number of modified messages decreases as well as increases, so it should be helpful for removing unread markers when another concurrently connected device updates the read status of a message.

**Comment by kaepora** [comment]
@flohdot Could you update the spec?

**Comment by flohdot** [comment]
`uploadedFilesAvailable` is now available in prod, and the spec changes have been pushed..

**Comment by kaepora** [comment]
:star:

**Comment by kaepora** [comment]
@flohdot `uploadedFilesAvailable` isn't working.

**Comment by flohdot** [comment]
It's firing for me in prod just fine. 

Looking at the client, I think you forgot to add support for the call in `socketworker.js`

**Comment by flohdot** [comment]
It's firing for me in prod just fine. 

Looking at the client, I think you forgot to add support for the call in `socketworker.js`
