### ISSUE TITLE
"Acknowledge" doesn't clear new message flag

### ISSUE THREAD

**Issue by 0xabad1dea** [PeerioTechnologies/peerio-client#9]
I tried to use the "acknowledge" button figuring that it would remove the green indicators of a new message, because I had certainly read it yet it remained "new" and this was annoying. However it left the new message indicators in place. 

edit: part of this may have been caused the edge case of only having one thread of messages total .

**Comment by Leodagan** [comment]
I think it appears with 1.0.1 because I haven't had this hours before. But yes I have the same green bar and I have only one conversation so maybe it's because we can't select another one.

**Comment by kaepora** [comment]
After some internal testing, we believe this problem is due to caching not handling read messages properly. Will investigate further.
