### ISSUE TITLE
Different background color for attachment in post in message

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#90]
Attachments are displayed with an icon and a name in the "post" box in the message display. 
It's difficult to see, and some people miss the attachment.

Maybe the blue background is for meta data (sender, time) and a different background for attachment display (light blue) ?
![capture](https://cloud.githubusercontent.com/assets/1250795/5887419/80b04b0c-a3cf-11e4-99be-4df53eae30f8.JPG)

**Comment by kaepora** [comment]
I guess we could make the font slightly larger.

**Comment by skylarnagao** [comment]
Different colors might be too 'noisy' and larger font seems like it would be out of proportion.

Alternative: Change the width of the blue header for the file name. Maybe length could match length of longest file name. More visually distinct e.g.

![2015-01-26_15-23-24](https://cloud.githubusercontent.com/assets/9948915/5907788/cd94b7e0-a56f-11e4-9e8d-e40791c9a885.png)

**Comment by skylarnagao** [comment]
This was resolved with **bolding** the file name.
