### ISSUE TITLE
Sort messages by last post time

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#92]
Messages view should be sorted by last received message time in the thread, not the creation time of the first message in the thread

**Comment by kaepora** [comment]
Isn't that how they're sorted currently?

**Comment by IpsmLorem** [comment]
No. 
They are sorted by the time of thread creation (first message), not the time of last message in the thread.

**Comment by IpsmLorem** [comment]
In fact it is, but the sorted displayed is only refreshed by closing the Chrome app and launching it again.
Furthermore, the green vertical bar for new message appears again, even if it's not a new message (one of the particpant change their First and Last name. Is that correlated ?)

**Comment by skylarnagao** [comment]
This has been solved, message threads now updated according to most recent messages received. Green notif bars seem to be resolved as well.
