### ISSUE TITLE
Bound messages to known devices

### ISSUE THREAD

**Issue by IpsmLorem** [PeerioTechnologies/peerio-client#93]
What about trying to bound messages to only known/approved devices of your recipient ?
Each devices would have a unique key used to encrypt a second time the message. The key could be shared with the server at device registration time.

A new message/file "decryptInfo" pairs would be encrypted by server to only devices involved in the thread.

Approving a new device would need to ask for the user through their email to accept the new authorized key and could be revoked later.

**Comment by skylarnagao** [comment]
Closing and will note as a related feature of "trusted devices" (#318).  

However, I'm trying to imagine a use case for this feature that isn't already addressed by enabling 2FA.
