### ISSUE TITLE
Destroy icon not clear enough

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#98]
Received comments saying the destroy icon was not clear. Consider design changes, more obvious flame, explosion, or TNT-plunger. 
![dynamite_plunger_icon](https://cloud.githubusercontent.com/assets/9948915/5909572/e9bff686-a57f-11e4-9d7b-651edba1cb80.png)

**Comment by kaepora** [comment]
Don't tempt me. I will replace all destroy icons with that 128x128 pixel art masterpiece.

**Comment by skylarnagao** [comment]
Have not received repeat comments on this issue. Closing for now. Will reopen if needed once we've done more UX testing.
