### ISSUE TITLE
Failure to add proper extensions when downloading files

### ISSUE THREAD

**Issue by skylarnagao** [PeerioTechnologies/peerio-client#99]
User reported using Windows client.
![noextensionwin](https://cloud.githubusercontent.com/assets/9948915/5909660/a7ad8a28-a580-11e4-9ba3-4c878f318c8c.png)

Also reproduced using Chrome client on Mac:
![noextensionchromeonosx](https://cloud.githubusercontent.com/assets/9948915/5909755/5f6a38dc-a581-11e4-88fa-2f0eaa5428c9.png)

**Comment by anri-asaturov** [comment]
I didn't manage to fix this issue yet, but here is the result of my investigation.

To reproduces issue you need
1. Run Peerio Chrome extension
2. Uncheck "Show all filename extension" in Finder Preferences.
![image](https://cloud.githubusercontent.com/assets/1479005/6033274/5e5db526-ac1c-11e4-97b5-73fefcc3bcc0.png)
3. Click "Save" on one of your Peerio files with extension.
4. When Save Dialog opens, "Hide Extension" checkbox should be checked.
![image](https://cloud.githubusercontent.com/assets/1479005/6033295/b22f3ea4-ac1c-11e4-918e-4c4b9da19618.png)
5. As the result, file is saved without extension 

Attempt to handle this was previously made with following code in `UI.downloadFile.js` file:
```javascript
39: if (!Peerio.file.getFileExtension(fileEntry.name)) {
40:	fileEntry.name = fileEntry.name + Peerio.file.getFileExtension(fileName)
41:	fileEntry.fullPath = fileEntry.fullPath + Peerio.file.getFileExtension(fileName)
...
```
But changing `fileEntry.name` and `fileEntry.fullPath` produces no result. Name remains the same. Which probably makes sense given the sandboxing, `fileEntry` was produced as the result of `chrome.fileSystem.chooseEntry` call and can't be changed. 
For the same reason attempts to rename file with `fileEntry.moveTo` after writing it didn't work. 

So I guess the workaround for now is to uncheck "hide extension" on file save dialog. 
Maybe we will have idea how to fix this later.

**Comment by skylarnagao** [comment]
Will leave open, write an FAQ for users for now.

Marked as "help wanted"

**Comment by kaepora** [comment]
Assigning @anri-asaturov

**Comment by skylarnagao** [comment]
Looks like the client is now automatically adding extensions on upload which effectively addresses the problem. Will reopen if users report additional trouble.
